drop table if exists items;
create table if exists items (
  item_id mediumint(8) unsigned not null default 0,
  name varchar(255) not null default '',
  quality tinyint(3) unsigned not null default 0,
  patch tinyint(3) unsigned not null default 0,
  class tinyint(3) unsigned not null default 0,
  subclass tinyint(3) unsigned not null default 0,
  description varchar(255) not null default '',
  display_id mediumint(8) unsigned not null default 0,
  flags int(10) unsigned not null default 0,
  buy_count tinyint(3) unsigned not null default 1,
  buy_price int(10) unsigned not null default 0,
  sell_price int(10) unsigned not null default 0,
  inventory_type tinyint(3) unsigned not null default 0,
  allowable_class mediumint(9) not null default -1,
  allowable_race mediumint(9) not null default -1,
  item_level tinyint(3) unsigned not null default 0,
  required_level tinyint(3) unsigned not null default 0,
  required_skill smallint(5) unsigned not null default 0,
  required_skill_rank smallint(5) unsigned not null default 0,
  required_spell mediumint(8) unsigned not null default 0,
  required_honor_rank mediumint(8) unsigned not null default 0,
  required_city_rank mediumint(8) unsigned not null default 0,
  required_reputation_faction smallint(5) unsigned not null default 0,
  required_reputation_rank smallint(5) unsigned not null default 0,
  max_count smallint(5) unsigned not null default 0,
  stackable smallint(5) unsigned not null default 1,
  container_slots tinyint(3) unsigned not null default 0,
  stat_type1 tinyint(3) unsigned not null default 0,
  stat_value1 smallint(6) not null default 0,
  stat_type2 tinyint(3) unsigned not null default 0,
  stat_value2 smallint(6) not null default 0,
  stat_type3 tinyint(3) unsigned not null default 0,
  stat_value3 smallint(6) not null default 0,
  stat_type4 tinyint(3) unsigned not null default 0,
  stat_value4 smallint(6) not null default 0,
  stat_type5 tinyint(3) unsigned not null default 0,
  stat_value5 smallint(6) not null default 0,
  stat_type6 tinyint(3) unsigned not null default 0,
  stat_value6 smallint(6) not null default 0,
  stat_type7 tinyint(3) unsigned not null default 0,
  stat_value7 smallint(6) not null default 0,
  stat_type8 tinyint(3) unsigned not null default 0,
  stat_value8 smallint(6) not null default 0,
  stat_type9 tinyint(3) unsigned not null default 0,
  stat_value9 smallint(6) not null default 0,
  stat_type10 tinyint(3) unsigned not null default 0,
  stat_value10 smallint(6) not null default 0,
  delay smallint(5) unsigned not null default 1000,
  range_mod float not null default 0,
  ammo_type tinyint(3) unsigned not null default 0,
  dmg_min1 float not null default 0,
  dmg_max1 float not null default 0,
  dmg_type1 tinyint(3) unsigned not null default 0,
  dmg_min2 float not null default 0,
  dmg_max2 float not null default 0,
  dmg_type2 tinyint(3) unsigned not null default 0,
  dmg_min3 float not null default 0,
  dmg_max3 float not null default 0,
  dmg_type3 tinyint(3) unsigned not null default 0,
  dmg_min4 float not null default 0,
  dmg_max4 float not null default 0,
  dmg_type4 tinyint(3) unsigned not null default 0,
  dmg_min5 float not null default 0,
  dmg_max5 float not null default 0,
  dmg_type5 tinyint(3) unsigned not null default 0,
  block mediumint(8) unsigned not null default 0,
  armor smallint(5) not null default 0,
  holy_res smallint(5) not null default 0,
  fire_res smallint(5) not null default 0,
  nature_res smallint(5) not null default 0,
  frost_res smallint(5) not null default 0,
  shadow_res smallint(5) not null default 0,
  arcane_res smallint(5) not null default 0,
  spellid_1 mediumint(8) unsigned not null default 0,
  spelltrigger_1 tinyint(3) unsigned not null default 0,
  spellcharges_1 tinyint(4) not null default 0,
  spellppmrate_1 float not null default 0,
  spellcooldown_1 int(11) not null default -1,
  spellcategory_1 smallint(5) unsigned not null default 0,
  spellcategorycooldown_1 int(11) not null default -1,
  spellid_2 mediumint(8) unsigned not null default 0,
  spelltrigger_2 tinyint(3) unsigned not null default 0,
  spellcharges_2 tinyint(4) not null default 0,
  spellppmrate_2 float not null default 0,
  spellcooldown_2 int(11) not null default -1,
  spellcategory_2 smallint(5) unsigned not null default 0,
  spellcategorycooldown_2 int(11) not null default -1,
  spellid_3 mediumint(8) unsigned not null default 0,
  spelltrigger_3 tinyint(3) unsigned not null default 0,
  spellcharges_3 tinyint(4) not null default 0,
  spellppmrate_3 float not null default 0,
  spellcooldown_3 int(11) not null default -1,
  spellcategory_3 smallint(5) unsigned not null default 0,
  spellcategorycooldown_3 int(11) not null default -1,
  spellid_4 mediumint(8) unsigned not null default 0,
  spelltrigger_4 tinyint(3) unsigned not null default 0,
  spellcharges_4 tinyint(4) not null default 0,
  spellppmrate_4 float not null default 0,
  spellcooldown_4 int(11) not null default -1,
  spellcategory_4 smallint(5) unsigned not null default 0,
  spellcategorycooldown_4 int(11) not null default -1,
  spellid_5 mediumint(8) unsigned not null default 0,
  spelltrigger_5 tinyint(3) unsigned not null default 0,
  spellcharges_5 tinyint(4) not null default 0,
  spellppmrate_5 float not null default 0,
  spellcooldown_5 int(11) not null default -1,
  spellcategory_5 smallint(5) unsigned not null default 0,
  spellcategorycooldown_5 int(11) not null default -1,
  bonding tinyint(3) unsigned not null default 0,
  page_text mediumint(8) unsigned not null default 0,
  page_language tinyint(3) unsigned not null default 0,
  page_material tinyint(3) unsigned not null default 0,
  start_quest mediumint(8) unsigned not null default 0,
  lock_id mediumint(8) unsigned not null default 0,
  material tinyint(4) not null default 0,
  sheath tinyint(3) unsigned not null default 0,
  random_property mediumint(8) unsigned not null default 0,
  set_id mediumint(8) unsigned not null default 0,
  max_durability smallint(5) unsigned not null default 0,
  area_bound mediumint(8) unsigned not null default 0,
  map_bound smallint(6) not null default 0,
  duration int(11) unsigned not null default 0,
  bag_family mediumint(9) not null default 0,
  disenchant_id mediumint(8) unsigned not null default 0,
  food_type tinyint(3) unsigned not null default 0,
  min_money_loot int(10) unsigned not null default 0,
  max_money_loot int(10) unsigned not null default 0,
  extra_flags tinyint(1) unsigned not null default 0,
  other_team_entry int(11) unsigned DEFAULT 1,
  KEY items_id (item_id),
  KEY items_name (name),
  KEY items_index (class)
) engine InnoDB DEFAULT CHARSET=utf8 COMMENT='Item System';